name: pinterest_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Clerk Authentication
  clerk_auth: ^0.0.13-beta
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/google.png
    - assets/icons/pinterest.png

  uses-material-design: true